version: '3'
services:
    web:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./web/cert.pem:/cert.pem:ro
            - ./web/key.pem:/key.pem:ro
            - ./web/certbot_challenge:/var/certbot_challenge:ro
            - ./web/www:/var/www:ro
        links:
            - api:api
    api:
        build: ./api
        ports:
            - 54321:12345
        links:
            - db:db
        volumes:
            - ./api/files:/var/files
        env_file:
            - ./env
    db:
        image: mysql
        volumes:
            - ./db/contents:/var/lib/mysql
            - ./db/backups:/backups
            - ./db/entrypoint:/docker-entrypoint-initdb.d:ro
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file:
            - ./env
